# Generated by Django 3.0.8 on 2020-07-12 08:39

import blog.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('hero_heading', models.CharField(max_length=100, null=True)),
                ('content', wagtail.core.fields.StreamField([('richtext_block', blog.blocks.RichTextBlock()), ('two_columns', wagtail.core.blocks.StructBlock([('left_column', blog.blocks.RichTextBlock(icon='arrow-right', label='Left column content')), ('right_column', blog.blocks.RichTextBlock(icon='arrow-right', label='Right column content'))])), ('imagetext_block', wagtail.core.blocks.StructBlock([('left_column', wagtail.images.blocks.ImageChooserBlock(icon='arrow-right', label='Left column image')), ('right_column', blog.blocks.RichTextBlock(icon='arrow-right', label='Right column text'))])), ('quote_block', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.TextBlock(icon='openquote', label='Quote')), ('attribution', wagtail.core.blocks.CharBlock(icon='user', label='Attribution'))])), ('gallery_block', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Gallery image'))]))], blank=True, null=True)),
                ('hero_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
