# Generated by Django 3.0.8 on 2020-07-14 10:48

import blog.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpage',
            name='content',
            field=wagtail.core.fields.StreamField([('richtext_block', blog.blocks.RichTextBlock()), ('two_columns', wagtail.core.blocks.StructBlock([('left_column', blog.blocks.RichTextBlock(icon='arrow-right', label='Left column content')), ('right_column', blog.blocks.RichTextBlock(icon='arrow-right', label='Right column content'))])), ('imagetext_block', wagtail.core.blocks.StructBlock([('left_column', wagtail.images.blocks.ImageChooserBlock(icon='arrow-right', label='Left column image')), ('right_column', blog.blocks.RichTextBlock(icon='arrow-right', label='Right column text'))])), ('quote_block', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.TextBlock(icon='openquote', label='Quote')), ('attribution', wagtail.core.blocks.CharBlock(icon='user', label='Attribution'))])), ('gallery_block', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Gallery image'))])), ('fullwidthimage_block', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Full-width image'))]))], blank=True, null=True),
        ),
    ]
