# Generated by Django 3.0.8 on 2020-07-25 04:09

import blog.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20200725_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpage',
            name='content',
            field=wagtail.core.fields.StreamField([('richtext_block', blog.blocks.RichTextBlock()), ('two_columns', wagtail.core.blocks.StructBlock([('left_column', blog.blocks.RichTextBlock(icon='arrow-left', label='Left column content')), ('right_column', blog.blocks.RichTextBlock(icon='arrow-right', label='Right column content'))])), ('imagetext_block', wagtail.core.blocks.StructBlock([('left_column', wagtail.images.blocks.ImageChooserBlock(icon='arrow-left', label='Left column image')), ('right_column', blog.blocks.RichTextBlock(icon='arrow-right', label='Right column text'))])), ('quote_block', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.TextBlock(icon='openquote', label='Quote')), ('attribution', wagtail.core.blocks.CharBlock(icon='user', label='Attribution'))])), ('gallery_block', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Gallery image'))])), ('fullwidthimage_block', blog.blocks.FullWidthImageBlock()), ('cta_block', wagtail.core.blocks.StructBlock([('cta_text', blog.blocks.RichTextBlock(icon='edit', label='CTA block copy')), ('cta_button', wagtail.core.blocks.TextBlock(icon='pick', label='CTA button text')), ('cta_link', wagtail.core.blocks.PageChooserBlock(icon='site', label='Link'))])), ('floatingcards_block', wagtail.core.blocks.StreamBlock([('float_card_left', blog.blocks.RichTextBlock(icon='arrow-left', label='Float card left')), ('float_card_right', blog.blocks.RichTextBlock(icon='arrow-right', label='Float card right'))])), ('faq_block', wagtail.core.blocks.StreamBlock([('faq', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.TextBlock(icon='help', label='FAQ Question')), ('answer', blog.blocks.RichTextBlock(icon='edit', label='FAQ Answer'))], icon='help'))]))], blank=True, null=True),
        ),
    ]
