# Generated by Django 3.0.8 on 2020-07-09 10:35

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200709_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='paragraph',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
