# Generated by Django 3.0.8 on 2020-07-09 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200709_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='intro',
            new_name='snippet',
        ),
    ]
