# Generated by Django 3.0.8 on 2020-07-10 11:48

import blog.blocks
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='body',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.core.fields.StreamField([('richtext_block', blog.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
