# Generated by Django 3.0.8 on 2020-07-10 13:19

import blog.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200711_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.core.fields.StreamField([('richtext_block', blog.blocks.RichTextBlock()), ('two_columns', wagtail.core.blocks.StructBlock([('left_column', blog.blocks.RichTextBlock(icon='arrow-right', label='Left column content')), ('right_column', blog.blocks.RichTextBlock(icon='arrow-right', label='Right column content'))]))], blank=True, null=True),
        ),
    ]
