# Generated by Django 3.0.8 on 2020-07-12 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200711_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=django.utils.timezone.now, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
