# Generated by Django 3.0.8 on 2020-07-12 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200712_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='seo_title',
            field=models.TextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
