# Generated by Django 3.0.8 on 2020-07-12 09:33

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_blogcategory_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
