# Generated by Django 3.0.8 on 2020-07-08 03:47

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepagegalleryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='intro',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
