# Generated by Django 3.0.8 on 2020-07-08 05:10

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0005_auto_20200708_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageFeaturedPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('featured_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='HomePageGalleryImage',
        ),
        migrations.AddField(
            model_name='homepagefeaturedposts',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_posts', to='home.HomePage'),
        ),
    ]
